---
- hosts: zabbix22
  remote_user: root
  vars_files:
    - 'defaults/postgresql.yml'
    - 'defaults/zabbix.yml'
    - 'defaults/httpd.yml'
  tasks:
    - include: 'tasks/main.yml'
  handlers:
    - include: 'handlers/main.yml'
  vars_prompt:
    ip_httpd: "On what ip should apache run ?"
