---
# Create Zabbix Database in PostgreSQL

- name: Add PostgreSQL .pgpass file
  template: src=.pgpass.j2 dest=/root/.pgpass mode=0600

- name: Upload PostgreSQL zabbix schema
  shell: psql -U zabbix < /usr/share/doc/zabbix-server-pgsql-{{ zbx_server_Version }}/create/{{item}}
  with_items:
        - schema.sql
        - images.sql
        - data.sql

- name: Cleanup PostgreSQL .pgpass file
  file: path=/root/.pgpass state=absent

#### ADD PGSQL DB & USER ####
#- name: Databases | Make sure the PostgreSQL databases are present
#  postgresql_db:
#    name: "{{ item.name }}"
#    encoding: "{{postgresql_encoding}}"
#    lc_collate: "{{postgresql_locale}}"
#    lc_ctype: "{{postgresql_locale}}"
#    template: "template0"
#    state: present
#  with_items: postgresql_databases
#  when: postgresql_databases|length > 0

#- name: Databases | Add hstore to the databases with the requirement
#  sudo: yes
#  sudo_user: "{{postgresql_admin_user}}"
#  shell: "psql {{item.name}} -c 'CREATE EXTENSION IF NOT EXISTS hstore;"
#  with_items: postgresql_databases
#  when: "item.hstore is defined and item.hstore == 'yes'"
#
#- name: PostgreSQL | Make sure the PostgreSQL users are present
#  postgresql_user:
#    name: "{{item.name}}"
#    password: "{{item.pass | default('pass')}}"
#    state: present
#    login_host: "{{item.host | default('localhost')}}"
#  with_items: postgresql_users
#  when: postgresql_users|length > 0
#
#- name: PostgreSQL | Update the user privileges
#  postgresql_user:
#    name: "{{item.name}}"
#    db: "{{item.db}}"
#    priv: "{{item.priv | default('ALL')}}"
#    state: present
#    login_host: "{{item.host | default('localhost')}}"
#  with_items: postgresql_user_privileges
#  when: postgresql_users|length > 0

