---
# handlers file for postgresql
- name: restart postgresql
  service: name=postgresql-{{ pg_version }} state=restarted
  tags:
    -postgres

- name: restart httpd
  service: name=httpd state=restarted
  tags:
    -http

- name: restart iptables
  action: service name=iptables state=restarted
